# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Camptocamp SA
org_slug: camptocamp
rebel_module_groups: []
repo_description: ''
repo_name: Odoo Legal Addons
repo_slug: odoo-legal
repo_website: https://github.com/camptocamp/odoo-legal
use_pyproject_toml: true
use_ruff: true

